/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etterem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author peti.dominik
 */
public class EtteremGUI extends javax.swing.JFrame {

    /**
     * Creates new form Etterem
     */
    private HashMap<JButton, String> tableButtons;
    private HashMap<JButton, String> billTableButtons;
    private ArrayList<Table> tableMenus;
    private Menu menu;
    private String selectedTable;
    private String selectedBillTable;
    
    
    public EtteremGUI() {
        this.tableButtons = new HashMap<>();
        this.billTableButtons = new HashMap<>();
        this.tableMenus = new ArrayList<>();
        this.menu = new Menu();
        this.selectedTable = TableNames.RED.displayName;
        this.selectedTable = TableNames.RED.displayName;
        
        initComponents();
        
        this.tableButtons.put(btnTableRed, TableNames.RED.displayName);
        this.tableButtons.put(btnTableGreen, TableNames.GREEN.displayName);
        this.tableButtons.put(btnTableBlue, TableNames.BLUE.displayName);
        this.tableButtons.put(btnTableWhite, TableNames.WHITE.displayName);
        
        this.billTableButtons.put(btnTableRedBill, TableNames.RED.displayName);
        this.billTableButtons.put(btnTableGreenBill, TableNames.GREEN.displayName);
        this.billTableButtons.put(btnTableBlueBill, TableNames.BLUE.displayName);
        this.billTableButtons.put(btnTableWhiteBill, TableNames.WHITE.displayName);
        
        for (TableNames TableName : TableNames.values()) {
            this.tableMenus.add(new Table(TableName.displayName));
        }
        
        this.menu.addMenuItem(new MenuItem("Babgulyás", 1700));
        this.menu.addMenuItem(new MenuItem("Rántott sajt", 1900));
        
        this.refreshJListMenu(this.jListMenuItems);
        this.refreshJListOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTableRed = new javax.swing.JButton();
        btnTableWhite = new javax.swing.JButton();
        btnTableGreen = new javax.swing.JButton();
        btnTableBlue = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMenuItems = new javax.swing.JList<>();
        panelOrder = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOrder = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListMenuEdit = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textNewMenuName = new javax.swing.JTextField();
        btnAddMenuItem = new javax.swing.JButton();
        spintNewMenuPrice = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnTableGreenBill = new javax.swing.JButton();
        btnTableWhiteBill = new javax.swing.JButton();
        btnTableRedBill = new javax.swing.JButton();
        btnTableBlueBill = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lblBillSum = new javax.swing.JLabel();
        btnPrintAll = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setName("Order"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Asztal"));

        btnTableRed.setBackground(new java.awt.Color(255, 51, 51));
        btnTableRed.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableRed.setForeground(new java.awt.Color(0, 0, 0));
        btnTableRed.setText("#");
        btnTableRed.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableRed.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableRed.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableRed.setPreferredSize(new java.awt.Dimension(40, 40));
        btnTableRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTable(evt);
            }
        });

        btnTableWhite.setBackground(new java.awt.Color(255, 255, 255));
        btnTableWhite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableWhite.setForeground(new java.awt.Color(0, 0, 0));
        btnTableWhite.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableWhite.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableWhite.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableWhite.setPreferredSize(new java.awt.Dimension(40, 40));
        btnTableWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTable(evt);
            }
        });

        btnTableGreen.setBackground(new java.awt.Color(153, 204, 0));
        btnTableGreen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableGreen.setForeground(new java.awt.Color(0, 0, 0));
        btnTableGreen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableGreen.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableGreen.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableGreen.setPreferredSize(new java.awt.Dimension(40, 40));
        btnTableGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTable(evt);
            }
        });

        btnTableBlue.setBackground(new java.awt.Color(51, 51, 255));
        btnTableBlue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableBlue.setForeground(new java.awt.Color(0, 0, 0));
        btnTableBlue.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableBlue.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableBlue.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableBlue.setPreferredSize(new java.awt.Dimension(40, 40));
        btnTableBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTable(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTableRed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTableGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTableBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTableWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTableRed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTableBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ételek"));

        jListMenuItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMenuItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListMenuItems);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendelés | "));

        jScrollPane2.setViewportView(jListOrder);

        javax.swing.GroupLayout panelOrderLayout = new javax.swing.GroupLayout(panelOrder);
        panelOrder.setLayout(panelOrderLayout);
        panelOrderLayout.setHorizontalGroup(
            panelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelOrderLayout.setVerticalGroup(
            panelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rendelés", jPanel1);

        jPanel2.setName("Menu"); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ételek"));

        jScrollPane3.setViewportView(jListMenuEdit);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Új étel"));

        jLabel2.setText("Ár:");

        jLabel1.setText("Név:");

        btnAddMenuItem.setText("Hozzáadás");
        btnAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMenuItemActionPerformed(evt);
            }
        });

        spintNewMenuPrice.setModel(new javax.swing.SpinnerNumberModel(5, 5, null, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddMenuItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textNewMenuName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(spintNewMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNewMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spintNewMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddMenuItem)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ételek", jPanel2);

        jPanel5.setName("Orders"); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Asztal"));

        btnTableGreenBill.setBackground(new java.awt.Color(153, 204, 0));
        btnTableGreenBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableGreenBill.setForeground(new java.awt.Color(0, 0, 0));
        btnTableGreenBill.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableGreenBill.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableGreenBill.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableGreenBill.setPreferredSize(new java.awt.Dimension(40, 40));

        btnTableWhiteBill.setBackground(new java.awt.Color(255, 255, 255));
        btnTableWhiteBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableWhiteBill.setForeground(new java.awt.Color(0, 0, 0));
        btnTableWhiteBill.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableWhiteBill.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableWhiteBill.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableWhiteBill.setPreferredSize(new java.awt.Dimension(40, 40));

        btnTableRedBill.setBackground(new java.awt.Color(255, 51, 51));
        btnTableRedBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableRedBill.setForeground(new java.awt.Color(0, 0, 0));
        btnTableRedBill.setText("#");
        btnTableRedBill.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableRedBill.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableRedBill.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableRedBill.setPreferredSize(new java.awt.Dimension(40, 40));

        btnTableBlueBill.setBackground(new java.awt.Color(51, 51, 255));
        btnTableBlueBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTableBlueBill.setForeground(new java.awt.Color(0, 0, 0));
        btnTableBlueBill.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTableBlueBill.setMaximumSize(new java.awt.Dimension(40, 40));
        btnTableBlueBill.setMinimumSize(new java.awt.Dimension(40, 40));
        btnTableBlueBill.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTableRedBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTableGreenBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTableBlueBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTableWhiteBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTableWhiteBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableBlueBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTableRedBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTableGreenBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        txtBill.setColumns(20);
        txtBill.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtBill.setRows(5);
        txtBill.setEnabled(false);
        jScrollPane4.setViewportView(txtBill);

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setText("Összesen");

        lblBillSum.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblBillSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnPrintAll.setText("Összes nyomtatása");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrintAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBillSum, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBillSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPrintAll)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Össz. számla", jPanel5);

        jMenu1.setText("Fileba mentés");

        jMenuItem1.setText("Rendelések mentése");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Étlap mentése");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changeTable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTable
        JButton source = (JButton) evt.getSource();
        
        this.selectedTable = this.tableButtons.get(source);
        
        for (Map.Entry<JButton, String> entry : this.tableButtons.entrySet()) {
            JButton key = entry.getKey();
            key.setText("");
        }
        
        source.setText("#");
        
        this.refreshJListOrder();
    }//GEN-LAST:event_changeTable

    private void jListMenuItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMenuItemsMouseClicked
        JList source = (JList) evt.getSource();
        
        //if (evt.getValueIsAdjusting()) {
        Optional<MenuItem> menuItemToAdd = this.menu.getMenuItemByName(source.getSelectedValue().toString());
        
        if (menuItemToAdd.isEmpty()) { return; }

        Table selectedTable = this.getTableByName(this.selectedTable);
            
        selectedTable.addToOrder(menuItemToAdd.get());

        this.refreshJListOrder();
        //}
    }//GEN-LAST:event_jListMenuItemsMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        JTabbedPane source = (JTabbedPane) evt.getSource();
        JPanel selected = (JPanel) source.getSelectedComponent();
        
        switch (selected.getName()) {
            case "Order":
                this.refreshJListMenu(this.jListMenuItems);
                this.refreshJListOrder();
                break;
            case "Menu":
                this.refreshJListMenu(this.jListMenuEdit);
                break;
            case "Orders":
                this.handleOrdersListing();
                break;
            default:
                throw new UnsupportedOperationException("Fejlesztés alatt...");
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMenuItemActionPerformed
        String name = this.textNewMenuName.getText();
        int price = (int) this.spintNewMenuPrice.getValue();
        
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Az étel neve nem lehet üres!");
            return;
        }
        
        if (this.menu.addMenuItem(new MenuItem(name, price))) {
            this.refreshJListMenu(this.jListMenuEdit);
        }
    }//GEN-LAST:event_btnAddMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Path path = Path.of("etelek.txt");
        String str = "";
        
        for (MenuItem menuItem : this.menu.getMenu()) {
            str += menuItem.toString() + "\n";
        }
        
        this.writeFile(path, str);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Path path = Path.of("rendeles.txt");
        String str = "";
        
        for (Table table : this.tableMenus) {
            
            str += this.capitalizeFirst(table.getTableName()) + "\n";
                    
            for (MenuItem order : table.getOrders()) {
                str += order.toString() + "\n";
            }
            str += "\n";
        }
        
        this.writeFile(path, str);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private String capitalizeFirst(String str) {
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
    
    private void writeFile(Path path, String str) {

        try {
            Files.deleteIfExists(path);
        } catch (IOException ex) {
            Logger.getLogger(EtteremGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Files.write(path, str.getBytes());
        } catch (IOException ex) {
            Logger.getLogger(EtteremGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refreshJListMenu(JList list) {
        DefaultListModel dLm = new DefaultListModel();
        
        for (MenuItem menuItem : this.menu.getMenu()) {
            dLm.addElement(menuItem.getName());
        }
        
        list.setModel(dLm);
    }
    
    private void refreshJListOrder() {
        String orderPanelText = "Rendelés | %s asztal".formatted(this.selectedTable);
        
        panelOrder.setBorder(BorderFactory.createTitledBorder(orderPanelText));
        DefaultListModel dLm = new DefaultListModel();
        
        Table table = this.getTableByName(this.selectedTable);
        
        for (MenuItem menuItem : table.getOrders()) {
            dLm.addElement(menuItem.getName());
        }
        
        jListOrder.setModel(dLm);
    }
    
    private Table getTableByName(String tableName) {
        int i = 0;
        while(i < this.tableMenus.size() && !this.tableMenus.get(i).getTableName().equals(tableName)) {
            i++;
        }
        
        return this.tableMenus.get(i);
    }
    
    private void handleOrdersListing() {
        try {
            Restaurant restaurant = new Restaurant();
            restaurant.loadMenuItems();
            restaurant.loadTables();
            
            Optional<Table> table = restaurant.getTableByName("piros");
            if (table.isPresent()) {
                refreshBill(table.get());
            }
            
            for (Map.Entry<JButton, String> entry : this.billTableButtons.entrySet()) {
                JButton key = entry.getKey();
                String val = entry.getValue();
                
                key.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JButton source = (JButton) e.getSource();
                        for (Map.Entry<JButton, String> entry : billTableButtons.entrySet()) {
                            JButton key = entry.getKey();
                            key.setText("");
                        }

                        source.setText("#");
        
                        String tableName = billTableButtons.get(source);

                        Optional<Table> table = restaurant.getTableByName(tableName);
                        if (table.isPresent()) {
                            refreshBill(table.get());
                        }
                    }
                });
                
            }
            
            btnPrintAll.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    writeBills(restaurant);
                }
            });
            
        } catch (IOException ex) {
            Logger.getLogger(EtteremGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refreshBill(Table table) {
        String txt = "";
        ArrayList<MenuItem> orders = table.getOrders();
        
        for (MenuItem item : orders) {
            txt += item.toString(45) + System.lineSeparator();
        }
        
        txtBill.setText(txt);
        lblBillSum.setText(String.valueOf(table.getPriceSum()) + " Ft");
    }
    
    private void writeBills(Restaurant restaurant) {
        System.out.println(restaurant.toString(30));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtteremGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtteremGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtteremGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtteremGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtteremGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMenuItem;
    private javax.swing.JButton btnPrintAll;
    private javax.swing.JButton btnTableBlue;
    private javax.swing.JButton btnTableBlueBill;
    private javax.swing.JButton btnTableGreen;
    private javax.swing.JButton btnTableGreenBill;
    private javax.swing.JButton btnTableRed;
    private javax.swing.JButton btnTableRedBill;
    private javax.swing.JButton btnTableWhite;
    private javax.swing.JButton btnTableWhiteBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListMenuEdit;
    private javax.swing.JList<String> jListMenuItems;
    private javax.swing.JList<String> jListOrder;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBillSum;
    private javax.swing.JPanel panelOrder;
    private javax.swing.JSpinner spintNewMenuPrice;
    private javax.swing.JTextField textNewMenuName;
    private javax.swing.JTextArea txtBill;
    // End of variables declaration//GEN-END:variables
}
